name: Build and Publish Image

on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build image using Buildah
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
          registry: ghcr.io

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: christoph00/container_nextcloud
          tags: ${{ matrix.arch }}
          arch: ${{ matrix.arch }}
          oci: true
          dockerfiles: ./Containerfile

      - name: Publish Image to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io

